= api-clients
:toc:

image:https://github.com/npo-poms/api-clients/workflows/build/badge.svg?[Build Status,link=https://github.com/npo-poms/api-clients/actions?query=workflow%3Abuild]
//image:https://travis-ci.com/npo-poms/api-clients.svg?[Build Status,link=https://travis-ci.com/npo-poms/api-clients]
image:https://img.shields.io/maven-central/v/nl.vpro.poms.api-clients/api-client-parent.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/search?q=g:%22nl.vpro.poms.api-clients%22]
image:https://codecov.io/gh/npo-poms/api-clients/branch/master/graph/badge.svg[codecov,link=https://codecov.io/gh/npo-poms/api-clients]
image:http://www.javadoc.io/badge/nl.vpro.poms.api-clients/frontend-api-client.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/nl.vpro.poms.api-clients/frontend-api-client]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/nl.vpro.poms.api-clients/api-client-parent.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/poms/api-clients/]


Java API clients for the POMS Rest API's (Frontend API, Backend API, Pages Publisher)

The clients are basicly generated using resteasy to proxy the actual service interface, and they are decorated with  some interceptors and similar techniques to arrange the appropriate authentication, to let the generated client automaticly fill common parameters, and things like that.

We also add a common way to instantiate (using the builder pattern) and configure them.

It is split up in several modules. These are the important ones:

* link:frontend-api-client[`frontend-api-client`] Provides clients for the https://rs.poms.omroep.nl[NPO Frontend API]

* link:media-backend-api-client[`media-backend-api-client`]. Provides a client for the https://api.poms.omroep.nl[POMS Backend API].

* link:pages-backend-api-client[`pages-backend-api-client`] Provides clients for the https://publish.pages.omroep.nl[Pages Publisher API]

* link:client-extras[`client-extras`] Provides some utilities which will make interaction with some calls simpler.

== bom
[source, xml]
----
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>nl.vpro.poms</groupId>
        <artifactId>poms-bom</artifactId>
        <version>8.3.1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>


...
<dependencies>
  <dependency>
    <groupId>nl.vpro.poms.api-clients</groupId>
    <artifactId>frontend-api-client</artifactId>
  </dependency>
  <dependency>
    <groupId>nl.vpro.poms.api-clients</groupId>
    <artifactId>media-backend-api-client</artifactId>
  </dependency>
  <dependency>
    <groupId>nl.vpro.poms.api-clients</groupId>
    <artifactId>pages-backend-api-client</artifactId>
  </dependency>
  <dependency>
    <groupId>nl.vpro.poms.api-clients</groupId>
    <artifactId>client-extras</artifactId>
  </dependency>
</dependencies>
----


== configuration

The clients can be configured by code and/or a configuration file in `${user.home}/conf/apiclient.properties`.

[source,java]
.frontend api
----
    NpoApiClients clients = NpoApiClients.configured(nl.vpro.util.Env.TEST).build();
    NpoApiMediaUtil util = new NpoApiMediaUtil(clients);
    try(CloseableIterator<MediaObject> i = util.iterate(null, "vpro-predictions")) {
      i.forEachRemaining(mediaObject -> {
         log.info("{}", i.next());
      });
    }

----

[source,java]
.backend api
----
 try (var client = MediaRestClient.configured(Env.PROD).build()) {
    MediaObject mediaObject = client.getFull("WO_VPRO_025678");
    log.info("{}", mediaObject);
 }
----

There are also 'providers' available to configure them easily via spring XML's or for example XML's of magnolia CMS (which uses guice)

== Versions


|===
|Version |java

| >= 8.x
| jakarta.*, java 17

| 7.11 branch
| support for javax will be from here.


| >= 7.5.x
|java 17

|7.4.x
|java 11

|===





== TODO

* Document how to wire via spring xml
